import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // ── Destinations ────────────────────────────────────────────────
  const destinations = await Promise.all([
    prisma.destination.upsert({
      where: { slug: "medellin" },
      update: {},
      create: {
        name: "Medellín",
        slug: "medellin",
        description: "La ciudad de la eterna primavera. Capital de Antioquia y epicentro de la transformación urbana de Colombia.",
        coverImage: "/img/featured_destinations/medellin-aerea.jpg",
        region: "Antioquia",
        sortOrder: 1,
      },
    }),
    prisma.destination.upsert({
      where: { slug: "guatape" },
      update: {},
      create: {
        name: "Guatapé",
        slug: "guatape",
        description: "El pueblo más colorido de Colombia, hogar de la Piedra del Peñol y el embalse más espectacular del país.",
        coverImage: "/img/featured_destinations/guatape.jpg",
        region: "Antioquia",
        sortOrder: 2,
      },
    }),
    prisma.destination.upsert({
      where: { slug: "santa-fe-de-antioquia" },
      update: {},
      create: {
        name: "Santa Fe de Antioquia",
        slug: "santa-fe-de-antioquia",
        description: "Ciudad colonial declarada Patrimonio Histórico Nacional. Calles empedradas, arquitectura española y clima cálido.",
        coverImage: "/img/featured_destinations/santa-fe-antioquia.jpg",
        region: "Antioquia",
        sortOrder: 3,
      },
    }),
    prisma.destination.upsert({
      where: { slug: "oriente-antioqueno" },
      update: {},
      create: {
        name: "Oriente Antioqueño",
        slug: "oriente-antioqueno",
        description: "Embalses, montañas y pueblos cafeteros. Un paraíso natural a menos de una hora de Medellín.",
        coverImage: "/img/featured_destinations/Rionegro-Antioquia.jpg",
        region: "Antioquia",
        sortOrder: 4,
      },
    }),
    prisma.destination.upsert({
      where: { slug: "doradal" },
      update: {},
      create: {
        name: "Doradal",
        slug: "doradal",
        description: "Puerta de entrada al Magdalena Medio. Parque Temático Hacienda Nápoles y naturaleza salvaje.",
        coverImage: "/img/featured_destinations/doradal-rio-claro.jpg",
        region: "Antioquia",
        sortOrder: 5,
      },
    }),
    prisma.destination.upsert({
      where: { slug: "jardin" },
      update: {},
      create: {
        name: "Jardín",
        slug: "jardin",
        description: "Considerado el pueblo más bonito de Antioquia. Café de origen, cascadas y arquitectura republicana intacta.",
        coverImage: "/img/featured_destinations/jardin.jpg",
        region: "Antioquia",
        sortOrder: 6,
      },
    }),
  ]);

  // ── Categories ──────────────────────────────────────────────────
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: "nightlife" },
      update: {},
      create: { name: "Vida Nocturna",      slug: "nightlife",       icon: "Moon",      color: "#0D1B3D", sortOrder: 1 },
    }),
    prisma.category.upsert({
      where: { slug: "city-tours" },
      update: {},
      create: { name: "Tours Urbanos",      slug: "city-tours",      icon: "Buildings", color: "#2BB7A6", sortOrder: 2 },
    }),
    prisma.category.upsert({
      where: { slug: "adventure" },
      update: {},
      create: { name: "Aventura",           slug: "adventure",       icon: "Mountain",  color: "#4B5E7A", sortOrder: 3 },
    }),
    prisma.category.upsert({
      where: { slug: "party" },
      update: {},
      create: { name: "Fiesta",             slug: "party",           icon: "Confetti",  color: "#FFC97A", sortOrder: 4 },
    }),
    prisma.category.upsert({
      where: { slug: "nature" },
      update: {},
      create: { name: "Naturaleza",         slug: "nature",          icon: "Leaf",      color: "#2BB7A6", sortOrder: 5 },
    }),
    prisma.category.upsert({
      where: { slug: "gastronomy" },
      update: {},
      create: { name: "Gastronomía",        slug: "gastronomy",      icon: "ForkKnife", color: "#FFC97A", sortOrder: 6 },
    }),
    prisma.category.upsert({
      where: { slug: "vip-experiences" },
      update: {},
      create: { name: "Experiencias VIP",   slug: "vip-experiences", icon: "Crown",     color: "#0D1B3D", sortOrder: 7 },
    }),
    prisma.category.upsert({
      where: { slug: "culture" },
      update: {},
      create: { name: "Cultura",            slug: "culture",         icon: "Landmark",  color: "#A8CBE6", sortOrder: 8 },
    }),
    prisma.category.upsert({
      where: { slug: "transportation" },
      update: {},
      create: { name: "Transporte",         slug: "transportation",  icon: "Bus",       color: "#4B5E7A", sortOrder: 9 },
    }),
  ]);

  // ── Operators ───────────────────────────────────────────────────
  const operators = await Promise.all([
    prisma.operator.upsert({
      where: { slug: "turtle-bus" },
      update: {},
      create: {
        name: "Turtle Bus",
        slug: "turtle-bus",
        description: "Tours temáticos únicos en Medellín a bordo de nuestro icónico bus.",
        commercialName: "Turtle Bus Medellín",
        contactEmail: "info@turtlebus.co",
        status: "active",
      },
    }),
    prisma.operator.upsert({
      where: { slug: "aeroturex" },
      update: {},
      create: {
        name: "Aeroturex",
        slug: "aeroturex",
        description: "City tours y experiencias urbanas de alta calidad en Medellín.",
        commercialName: "Aeroturex Colombia",
        contactEmail: "info@aeroturex.co",
        status: "active",
      },
    }),
    prisma.operator.upsert({
      where: { slug: "guatape-travel" },
      update: {},
      create: {
        name: "Guatapé Travel",
        slug: "guatape-travel",
        description: "Especialistas en tours a Guatapé, la Piedra del Peñol y alrededores.",
        commercialName: "Guatapé Travel",
        contactEmail: "info@guatapetravel.co",
        status: "active",
      },
    }),
    prisma.operator.upsert({
      where: { slug: "chivas-celebraciones" },
      update: {},
      create: {
        name: "Chivas & Trolley Tours",
        slug: "chivas-celebraciones",
        description: "Experiencias de fiesta, chivas y eventos especiales en Medellín.",
        commercialName: "Chivas y Celebraciones",
        contactEmail: "info@chivasmedellin.co",
        status: "active",
      },
    }),
  ]);

  // ── Shortcuts ───────────────────────────────────────────────────
  const [destMedellin, destGuatape, destSantaFe] = destinations;
  const [catNightlife, catCityTours, catAdventure, catParty, catNature, , catVip, catCulture, catTransport] = categories;
  const [opTurtleBus, opAeroturex, opGuatapeTravel, opChivas] = operators;

  // ── Tours ───────────────────────────────────────────────────────
  const toursData = [
    {
      operatorId: opTurtleBus.id,
      destinationId: destMedellin.id,
      title: "Turtle Bus City Tour",
      slug: "turtle-bus-city-tour",
      shortDescription: "Recorre los barrios más icónicos de Medellín a bordo de nuestro colorido bus temático.",
      priceFrom: 85000,
      durationMinutes: 180,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["09:00", "14:00"],
      returnTime: "17:00",
      isFullDay: false,
      zone: "sur",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "cultural", "familiar", "urbano"],
      categories: [catCityTours.id, catTransport.id],
    },
    {
      operatorId: opTurtleBus.id,
      destinationId: destMedellin.id,
      title: "Turtle Bus Nightlife Tour",
      slug: "turtle-bus-nightlife-tour",
      shortDescription: "Descubre la vibrante vida nocturna de Medellín desde el Turtle Bus con paradas en los mejores spots.",
      priceFrom: 120000,
      durationMinutes: 240,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["21:00"],
      returnTime: "01:00",
      isFullDay: false,
      zone: "sur",
      physicalIntensity: "low",
      operatingDays: [4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["noche", "adultos", "festivo", "grupal"],
      categories: [catNightlife.id, catTransport.id],
    },
    {
      operatorId: opAeroturex.id,
      destinationId: destMedellin.id,
      title: "Medellín Panorámica",
      slug: "medellin-panoramica",
      shortDescription: "Los mejores miradores, barrios históricos y rincones secretos de Medellín en un tour exclusivo.",
      priceFrom: 75000,
      durationMinutes: 240,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["09:00", "13:00"],
      returnTime: "17:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: true,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "cultural", "familiar", "fotográfico"],
      categories: [catCityTours.id, catCulture.id],
    },
    {
      operatorId: opAeroturex.id,
      destinationId: destMedellin.id,
      title: "Comuna 13 Tour",
      slug: "comuna-13-tour",
      shortDescription: "Historia, arte urbano, transformación social y las escaleras eléctricas más famosas de Latinoamérica.",
      priceFrom: 65000,
      durationMinutes: 180,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["09:00", "14:00"],
      returnTime: "17:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "medium",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "cultural", "histórico", "fotográfico"],
      categories: [catCulture.id, catCityTours.id],
    },
    {
      operatorId: opGuatapeTravel.id,
      destinationId: destGuatape.id,
      title: "Guatapé Full Day",
      slug: "guatape-full-day",
      shortDescription: "El pueblo más colorido de Colombia + subida a la Piedra del Peñol + tour en lancha por el embalse.",
      priceFrom: 130000,
      durationMinutes: 600,
      isFeatured: true,
      isOffer: true,
      departureTimes: ["07:00"],
      returnTime: "17:30",
      isFullDay: true,
      zone: "fuera-medellin",
      physicalIntensity: "medium",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: true,
      bookingAdvanceDays: 2,
      tags: ["día-completo", "naturaleza", "familiar", "fotográfico", "acuático"],
      categories: [catNature.id, catAdventure.id],
    },
    {
      operatorId: opGuatapeTravel.id,
      destinationId: destGuatape.id,
      title: "Tour en Lancha por el Embalse",
      slug: "tour-lancha-embalse-guatape",
      shortDescription: "Navega por las cristalinas aguas del embalse de Guatapé y conoce las islas de sus alrededores.",
      priceFrom: 95000,
      durationMinutes: 120,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["10:00", "13:00", "15:00"],
      returnTime: "17:00",
      isFullDay: false,
      zone: "fuera-medellin",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "acuático", "familiar", "naturaleza"],
      categories: [catNature.id, catAdventure.id],
    },
    {
      operatorId: opChivas.id,
      destinationId: destMedellin.id,
      title: "Chiva Parrandera Medellín",
      slug: "chiva-parrandera-medellin",
      shortDescription: "La rumba más auténtica de Medellín a bordo de una chiva tradicional con música en vivo y trago incluido.",
      priceFrom: 150000,
      durationMinutes: 300,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["20:00"],
      returnTime: "01:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "low",
      operatingDays: [4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["noche", "festivo", "adultos", "grupal", "cultural"],
      categories: [catParty.id, catNightlife.id],
    },
    {
      operatorId: opChivas.id,
      destinationId: destMedellin.id,
      title: "Chiva VIP Privada",
      slug: "chiva-vip-privada",
      shortDescription: "Chiva exclusiva para grupos privados, despedidas de soltero/a, cumpleaños y eventos corporativos.",
      priceFrom: 800000,
      durationMinutes: 360,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["19:00", "21:00"],
      returnTime: "02:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: true,
      bookingAdvanceDays: 3,
      tags: ["noche", "privado", "premium", "eventos", "adultos"],
      categories: [catVip.id, catParty.id],
    },
    {
      operatorId: opAeroturex.id,
      destinationId: destSantaFe.id,
      title: "Santa Fe de Antioquia Colonial",
      slug: "santa-fe-antioquia-colonial",
      shortDescription: "Descubre la ciudad colonial más importante de Antioquia con guía experto y almuerzo típico incluido.",
      priceFrom: 110000,
      durationMinutes: 480,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["07:00"],
      returnTime: "16:00",
      isFullDay: true,
      zone: "fuera-medellin",
      physicalIntensity: "low",
      operatingDays: [2, 3, 4, 5, 6, 7],
      pickupIncluded: true,
      bookingAdvanceDays: 2,
      tags: ["día-completo", "cultural", "histórico", "familiar", "gastronómico"],
      categories: [catCulture.id, catCityTours.id],
    },
    {
      operatorId: opTurtleBus.id,
      destinationId: destMedellin.id,
      title: "Medellín VIP Experience",
      slug: "medellin-vip-experience",
      shortDescription: "Restaurantes gourmet, miradores exclusivos, transporte premium y experiencias que no están en los mapas.",
      priceFrom: 350000,
      durationMinutes: 480,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["10:00"],
      returnTime: "19:00",
      isFullDay: true,
      zone: "sur",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: true,
      bookingAdvanceDays: 3,
      tags: ["día-completo", "premium", "gastronómico", "romántico", "privado"],
      categories: [catVip.id, catCityTours.id],
    },
    {
      operatorId: opAeroturex.id,
      destinationId: destMedellin.id,
      title: "Tour en Bici por El Poblado",
      slug: "tour-bici-el-poblado",
      shortDescription: "Pedalea por los barrios más trendy de Medellín: El Poblado, Provenza y el corazón de la ciudad.",
      priceFrom: 55000,
      durationMinutes: 180,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["08:00", "10:00"],
      returnTime: "13:00",
      isFullDay: false,
      zone: "sur",
      physicalIntensity: "medium",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "activo", "urbano", "fotográfico"],
      categories: [catCityTours.id, catAdventure.id],
    },
    {
      operatorId: opTurtleBus.id,
      destinationId: destMedellin.id,
      title: "Tour Pablo Escobar",
      slug: "tour-pablo-escobar",
      shortDescription: "Conoce la historia real del narcotráfico colombiano con perspectiva crítica, educativa y local.",
      priceFrom: 70000,
      durationMinutes: 240,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["09:00", "14:00"],
      returnTime: "18:00",
      isFullDay: false,
      zone: "norte",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "cultural", "histórico"],
      categories: [catCulture.id, catCityTours.id],
    },
    {
      operatorId: opAeroturex.id,
      destinationId: destMedellin.id,
      title: "Parapente sobre Medellín",
      slug: "parapente-medellin",
      shortDescription: "Vuela sobre el Valle de Aburrá en parapente en tándem y admira Medellín desde las alturas.",
      priceFrom: 180000,
      durationMinutes: 60,
      isFeatured: true,
      isOffer: false,
      departureTimes: ["07:00", "09:00", "11:00", "14:00"],
      returnTime: "16:00",
      isFullDay: false,
      zone: "norte",
      physicalIntensity: "high",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "adrenalina", "aventura", "fotográfico"],
      categories: [catAdventure.id, catCityTours.id],
    },
    {
      operatorId: opGuatapeTravel.id,
      destinationId: destGuatape.id,
      title: "Kayak en el Embalse de Guatapé",
      slug: "kayak-embalse-guatape",
      shortDescription: "Explora las orillas del embalse en kayak y descubre rincones inaccesibles desde tierra.",
      priceFrom: 80000,
      durationMinutes: 150,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["09:00", "14:00"],
      returnTime: "16:30",
      isFullDay: false,
      zone: "fuera-medellin",
      physicalIntensity: "medium",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["mañana", "tarde", "acuático", "aventura", "naturaleza"],
      categories: [catAdventure.id, catNature.id],
    },
    {
      operatorId: opGuatapeTravel.id,
      destinationId: destGuatape.id,
      title: "Atardecer en el Peñol",
      slug: "atardecer-penol-guatape",
      shortDescription: "Sube a la Piedra del Peñol al atardecer y vive la magia del embalse teñido de naranja y rojo.",
      priceFrom: 60000,
      durationMinutes: 120,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["16:00"],
      returnTime: "18:30",
      isFullDay: false,
      zone: "fuera-medellin",
      physicalIntensity: "medium",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 1,
      tags: ["tarde", "fotográfico", "romántico", "naturaleza"],
      categories: [catNature.id, catAdventure.id],
    },
    {
      operatorId: opChivas.id,
      destinationId: destMedellin.id,
      title: "Chiva Fiestera Cumpleaños",
      slug: "chiva-fiestera-cumpleanos",
      shortDescription: "Celebra tu cumpleaños o despedida en nuestra chiva parrandera con decoración, DJ y trago incluido.",
      priceFrom: 200000,
      durationMinutes: 240,
      isFeatured: false,
      isOffer: false,
      departureTimes: ["19:00", "21:00"],
      returnTime: "01:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "low",
      operatingDays: [1, 2, 3, 4, 5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 2,
      tags: ["noche", "festivo", "adultos", "grupal", "privado", "eventos"],
      categories: [catParty.id, catNightlife.id],
    },
    {
      operatorId: opChivas.id,
      destinationId: destMedellin.id,
      title: "Chiva de las Flores",
      slug: "chiva-de-las-flores",
      shortDescription: "Recorre las calles de Medellín en la legendaria Chiva de las Flores durante la Feria de las Flores.",
      priceFrom: 130000,
      durationMinutes: 180,
      isFeatured: false,
      isOffer: true,
      departureTimes: ["18:00", "20:00"],
      returnTime: "23:00",
      isFullDay: false,
      zone: "centro",
      physicalIntensity: "low",
      operatingDays: [5, 6, 7],
      pickupIncluded: false,
      bookingAdvanceDays: 2,
      tags: ["noche", "festivo", "cultural", "familiar", "grupal"],
      categories: [catParty.id, catCulture.id],
    },
  ];

  for (const tourData of toursData) {
    const { categories: tourCategories, ...data } = tourData;
    await prisma.tour.upsert({
      where: { slug: data.slug },
      update: {},
      create: {
        ...data,
        status: "published",
        publishedAt: new Date(),
        tourCategories: {
          create: tourCategories.map((categoryId) => ({ categoryId })),
        },
      },
    });
  }

  console.log("✅ Seed complete.");
  console.log(`   ${destinations.length} destinos`);
  console.log(`   ${categories.length} categorías`);
  console.log(`   ${operators.length} operadores`);
  console.log(`   ${toursData.length} tours`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

