import type { TourSummary, TourDetail, Destination, Category } from "./types";

export const mockCategories: Category[] = [
  { id: "1", name: "Vida Nocturna",           slug: "nightlife",       icon: "Moon",      color: "#0D1B3D" },
  { id: "2", name: "Tours Urbanos",           slug: "city-tours",      icon: "Buildings", color: "#2BB7A6" },
  { id: "3", name: "Aventura",                slug: "adventure",       icon: "Mountain",  color: "#4B5E7A" },
  { id: "4", name: "Fiesta",                  slug: "party",           icon: "Confetti",  color: "#FFC97A" },
  { id: "5", name: "Naturaleza",              slug: "nature",          icon: "Leaf",      color: "#2BB7A6" },
  { id: "6", name: "Gastronomía",             slug: "gastronomy",      icon: "ForkKnife", color: "#FFC97A" },
  { id: "7", name: "Experiencias VIP",        slug: "vip-experiences", icon: "Crown",     color: "#0D1B3D" },
  { id: "8", name: "Cultura",                 slug: "culture",         icon: "Landmark",  color: "#A8CBE6" },
  { id: "9", name: "Transporte",              slug: "transportation",  icon: "Bus",       color: "#4B5E7A" },
];

export const mockDestinations: Destination[] = [
  {
    id: "1",
    name: "Medellín",
    slug: "medellin",
    description: "La ciudad de la eterna primavera. Capital de Antioquia y epicentro de la transformación urbana de Colombia.",
    coverImage: "/img/featured_destinations/medellin-aerea.jpg",
    region: "Antioquia",
  },
  {
    id: "2",
    name: "Guatapé",
    slug: "guatape",
    description: "El pueblo más colorido de Colombia, hogar de la Piedra del Peñol y el embalse más espectacular del país.",
    coverImage: "/img/featured_destinations/guatape.jpg",
    region: "Antioquia",
  },
  {
    id: "3",
    name: "Santa Fe de Antioquia",
    slug: "santa-fe-de-antioquia",
    description: "Ciudad colonial declarada Patrimonio Histórico Nacional. Calles empedradas, arquitectura española y clima cálido.",
    coverImage: "/img/featured_destinations/santa-fe-antioquia.jpg",
    region: "Antioquia",
  },
  {
    id: "4",
    name: "Oriente Antioqueño",
    slug: "oriente-antioqueno",
    description: "Embalses, montañas y pueblos cafeteros. Un paraíso natural a menos de una hora de Medellín.",
    coverImage: "/img/featured_destinations/Rionegro-Antioquia.jpg",
    region: "Antioquia",
  },
  {
    id: "5",
    name: "Doradal",
    slug: "doradal",
    description: "Puerta de entrada al Magdalena Medio. Parque Temático Hacienda Nápoles y naturaleza salvaje.",
    coverImage: "/img/featured_destinations/doradal-rio-claro.jpg",
    region: "Antioquia",
  },
  {
    id: "6",
    name: "Jardín",
    slug: "jardin",
    description: "Considerado el pueblo más bonito de Antioquia. Café de origen, cascadas y arquitectura republicana intacta.",
    coverImage: "/img/featured_destinations/jardin.jpg",
    region: "Antioquia",
  },
];

const destMedellin = { id: "1", name: "Medellín", slug: "medellin", region: "Antioquia" };
const destGuatape = { id: "2", name: "Guatapé", slug: "guatape", region: "Antioquia" };
const destSantaFe = { id: "3", name: "Santa Fe de Antioquia", slug: "santa-fe-de-antioquia", region: "Antioquia" };

const opTurtleBus = { id: "1", name: "Turtle Bus", slug: "turtle-bus", logoUrl: null };
const opAeroturex = { id: "2", name: "Aeroturex", slug: "aeroturex", logoUrl: null };
const opGuatape  = { id: "3", name: "Guatapé Travel", slug: "guatape-travel", logoUrl: null };
const opChivas   = { id: "4", name: "Chivas & Trolley Tours", slug: "chivas-celebraciones", logoUrl: null };

export const mockTours: TourSummary[] = [
  {
    id: "1",
    title: "Turtle Bus City Tour",
    slug: "turtle-bus-city-tour",
    shortDescription: "Recorre los barrios más icónicos de Medellín a bordo de nuestro colorido bus temático.",
    priceFrom: 85000,
    currency: "COP",
    durationMinutes: 180,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opTurtleBus,
    categories: [{ id: "2", name: "Tours Urbanos", slug: "city-tours", color: "#2BB7A6" }],
    coverImage: "https://picsum.photos/seed/medellin-bus/800/500",
    rating: 4.8,
    reviewCount: 124,
    departureTimes: ["09:00", "14:00"],
    returnTime: "17:00",
    isFullDay: false,
    zone: "sur",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "cultural", "familiar", "urbano"],
  },
  {
    id: "2",
    title: "Turtle Bus Nightlife Tour",
    slug: "turtle-bus-nightlife-tour",
    shortDescription: "Descubre la vibrante vida nocturna de Medellín desde el Turtle Bus con paradas en los mejores spots.",
    priceFrom: 120000,
    currency: "COP",
    durationMinutes: 240,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opTurtleBus,
    categories: [{ id: "1", name: "Vida Nocturna", slug: "nightlife", color: "#0D1B3D" }],
    coverImage: "https://picsum.photos/seed/medellin-night/800/500",
    rating: 4.9,
    reviewCount: 89,
    departureTimes: ["21:00"],
    returnTime: "01:00",
    isFullDay: false,
    zone: "sur",
    physicalIntensity: "low",
    operatingDays: [4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["noche", "adultos", "festivo", "grupal"],
  },
  {
    id: "3",
    title: "Medellín Panorámica",
    slug: "medellin-panoramica",
    shortDescription: "Los mejores miradores, barrios históricos y rincones secretos de Medellín en un tour exclusivo.",
    priceFrom: 75000,
    currency: "COP",
    durationMinutes: 240,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opAeroturex,
    categories: [{ id: "2", name: "Tours Urbanos", slug: "city-tours", color: "#2BB7A6" }],
    coverImage: "https://picsum.photos/seed/medellin-view/800/500",
    rating: 4.7,
    reviewCount: 203,
    departureTimes: ["09:00", "13:00"],
    returnTime: "17:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: true,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "cultural", "familiar", "fotográfico"],
  },
  {
    id: "4",
    title: "Comuna 13 Tour",
    slug: "comuna-13-tour",
    shortDescription: "Historia, arte urbano, transformación social y las escaleras eléctricas más famosas de Latinoamérica.",
    priceFrom: 65000,
    currency: "COP",
    durationMinutes: 180,
    isFeatured: false,
    isOffer: false,
    destination: destMedellin,
    operator: opAeroturex,
    categories: [{ id: "8", name: "Cultura", slug: "culture", color: "#A8CBE6" }],
    coverImage: "https://picsum.photos/seed/graffiti-art/800/500",
    rating: 4.9,
    reviewCount: 312,
    departureTimes: ["09:00", "14:00"],
    returnTime: "17:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "medium",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "cultural", "histórico", "fotográfico"],
  },
  {
    id: "5",
    title: "Guatapé Full Day",
    slug: "guatape-full-day",
    shortDescription: "El pueblo más colorido de Colombia + subida a la Piedra del Peñol + tour en lancha por el embalse.",
    priceFrom: 130000,
    currency: "COP",
    durationMinutes: 600,
    isFeatured: true,
    isOffer: true,
    destination: destGuatape,
    operator: opGuatape,
    categories: [{ id: "5", name: "Naturaleza", slug: "nature", color: "#2BB7A6" }],
    coverImage: "https://picsum.photos/seed/guatape-rock/800/500",
    rating: 4.9,
    reviewCount: 445,
    departureTimes: ["07:00"],
    returnTime: "17:30",
    isFullDay: true,
    zone: "fuera-medellin",
    physicalIntensity: "medium",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: true,
    bookingAdvanceDays: 2,
    tags: ["día-completo", "naturaleza", "familiar", "fotográfico", "acuático"],
  },
  {
    id: "6",
    title: "Tour en Lancha por el Embalse",
    slug: "tour-lancha-embalse-guatape",
    shortDescription: "Navega por las cristalinas aguas del embalse de Guatapé y conoce las islas de sus alrededores.",
    priceFrom: 95000,
    currency: "COP",
    durationMinutes: 120,
    isFeatured: false,
    isOffer: false,
    destination: destGuatape,
    operator: opGuatape,
    categories: [{ id: "3", name: "Aventura", slug: "adventure", color: "#4B5E7A" }],
    coverImage: "https://picsum.photos/seed/lake-boat/800/500",
    rating: 4.6,
    reviewCount: 78,
    departureTimes: ["10:00", "13:00", "15:00"],
    returnTime: "17:00",
    isFullDay: false,
    zone: "fuera-medellin",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "acuático", "familiar", "naturaleza"],
  },
  {
    id: "7",
    title: "Chiva Parrandera Medellín",
    slug: "chiva-parrandera-medellin",
    shortDescription: "La rumba más auténtica de Medellín a bordo de una chiva tradicional con música en vivo y trago incluido.",
    priceFrom: 150000,
    currency: "COP",
    durationMinutes: 300,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opChivas,
    categories: [{ id: "4", name: "Fiesta", slug: "party", color: "#FFC97A" }],
    coverImage: "https://picsum.photos/seed/party-bus/800/500",
    rating: 4.8,
    reviewCount: 167,
    departureTimes: ["20:00"],
    returnTime: "01:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "low",
    operatingDays: [4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["noche", "festivo", "adultos", "grupal", "cultural"],
  },
  {
    id: "8",
    title: "Chiva VIP Privada",
    slug: "chiva-vip-privada",
    shortDescription: "Chiva exclusiva para grupos privados, despedidas de soltero/a, cumpleaños y eventos corporativos.",
    priceFrom: 800000,
    currency: "COP",
    durationMinutes: 360,
    isFeatured: false,
    isOffer: false,
    destination: destMedellin,
    operator: opChivas,
    categories: [{ id: "7", name: "Experiencias VIP", slug: "vip-experiences", color: "#0D1B3D" }],
    coverImage: "https://picsum.photos/seed/vip-event/800/500",
    rating: 5.0,
    reviewCount: 34,
    departureTimes: ["19:00", "21:00"],
    returnTime: "02:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: true,
    bookingAdvanceDays: 3,
    tags: ["noche", "privado", "premium", "eventos", "adultos"],
  },
  {
    id: "9",
    title: "Santa Fe de Antioquia Colonial",
    slug: "santa-fe-antioquia-colonial",
    shortDescription: "Descubre la ciudad colonial más importante de Antioquia con guía experto y almuerzo típico incluido.",
    priceFrom: 110000,
    currency: "COP",
    durationMinutes: 480,
    isFeatured: false,
    isOffer: false,
    destination: destSantaFe,
    operator: opAeroturex,
    categories: [{ id: "8", name: "Cultura", slug: "culture", color: "#A8CBE6" }],
    coverImage: "https://picsum.photos/seed/colonial-church/800/500",
    rating: 4.5,
    reviewCount: 56,
    departureTimes: ["07:00"],
    returnTime: "16:00",
    isFullDay: true,
    zone: "fuera-medellin",
    physicalIntensity: "low",
    operatingDays: [2, 3, 4, 5, 6, 7],
    pickupIncluded: true,
    bookingAdvanceDays: 2,
    tags: ["día-completo", "cultural", "histórico", "familiar", "gastronómico"],
  },
  {
    id: "10",
    title: "Medellín VIP Experience",
    slug: "medellin-vip-experience",
    shortDescription: "Restaurantes gourmet, miradores exclusivos, transporte premium y experiencias que no están en los mapas.",
    priceFrom: 350000,
    currency: "COP",
    durationMinutes: 480,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opTurtleBus,
    categories: [{ id: "7", name: "Experiencias VIP", slug: "vip-experiences", color: "#0D1B3D" }],
    coverImage: "https://picsum.photos/seed/luxury-city/800/500",
    rating: 4.9,
    reviewCount: 41,
    departureTimes: ["10:00"],
    returnTime: "19:00",
    isFullDay: true,
    zone: "sur",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: true,
    bookingAdvanceDays: 3,
    tags: ["día-completo", "premium", "gastronómico", "romántico", "privado"],
  },
  {
    id: "11",
    title: "Tour en Bici por El Poblado",
    slug: "tour-bici-el-poblado",
    shortDescription: "Pedalea por los barrios más trendy de Medellín: El Poblado, Provenza y el corazón de la ciudad.",
    priceFrom: 55000,
    currency: "COP",
    durationMinutes: 180,
    isFeatured: false,
    isOffer: false,
    destination: destMedellin,
    operator: opAeroturex,
    categories: [{ id: "2", name: "Tours Urbanos", slug: "city-tours", color: "#2BB7A6" }],
    coverImage: "https://picsum.photos/seed/bike-city/800/500",
    rating: 4.7,
    reviewCount: 93,
    departureTimes: ["08:00", "10:00"],
    returnTime: "13:00",
    isFullDay: false,
    zone: "sur",
    physicalIntensity: "medium",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "activo", "urbano", "fotográfico"],
  },
  {
    id: "12",
    title: "Tour Pablo Escobar",
    slug: "tour-pablo-escobar",
    shortDescription: "Conoce la historia real del narcotráfico colombiano con perspectiva crítica, educativa y local.",
    priceFrom: 70000,
    currency: "COP",
    durationMinutes: 240,
    isFeatured: false,
    isOffer: false,
    destination: destMedellin,
    operator: opTurtleBus,
    categories: [{ id: "8", name: "Cultura", slug: "culture", color: "#A8CBE6" }],
    coverImage: "https://picsum.photos/seed/medellin-history/800/500",
    rating: 4.6,
    reviewCount: 287,
    departureTimes: ["09:00", "14:00"],
    returnTime: "18:00",
    isFullDay: false,
    zone: "norte",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "cultural", "histórico"],
  },
  {
    id: "13",
    title: "Parapente sobre Medellín",
    slug: "parapente-medellin",
    shortDescription: "Vuela sobre el Valle de Aburrá en parapente en tándem y admira Medellín desde las alturas.",
    priceFrom: 180000,
    currency: "COP",
    durationMinutes: 60,
    isFeatured: true,
    isOffer: false,
    destination: destMedellin,
    operator: opAeroturex,
    categories: [{ id: "3", name: "Aventura", slug: "adventure", color: "#4B5E7A" }],
    coverImage: "https://picsum.photos/seed/paragliding/800/500",
    rating: 4.9,
    reviewCount: 156,
    departureTimes: ["07:00", "09:00", "11:00", "14:00"],
    returnTime: "16:00",
    isFullDay: false,
    zone: "norte",
    physicalIntensity: "high",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "adrenalina", "aventura", "fotográfico"],
  },
  {
    id: "14",
    title: "Kayak en el Embalse de Guatapé",
    slug: "kayak-embalse-guatape",
    shortDescription: "Explora las orillas del embalse en kayak y descubre rincones inaccesibles desde tierra.",
    priceFrom: 80000,
    currency: "COP",
    durationMinutes: 150,
    isFeatured: false,
    isOffer: false,
    destination: destGuatape,
    operator: opGuatape,
    categories: [{ id: "3", name: "Aventura", slug: "adventure", color: "#4B5E7A" }],
    coverImage: "https://picsum.photos/seed/kayak-lake/800/500",
    rating: 4.8,
    reviewCount: 44,
    departureTimes: ["09:00", "14:00"],
    returnTime: "16:30",
    isFullDay: false,
    zone: "fuera-medellin",
    physicalIntensity: "medium",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["mañana", "tarde", "acuático", "aventura", "naturaleza"],
  },
  {
    id: "15",
    title: "Atardecer en el Peñol",
    slug: "atardecer-penol-guatape",
    shortDescription: "Sube a la Piedra del Peñol al atardecer y vive la magia del embalse teñido de naranja y rojo.",
    priceFrom: 60000,
    currency: "COP",
    durationMinutes: 120,
    isFeatured: false,
    isOffer: false,
    destination: destGuatape,
    operator: opGuatape,
    categories: [{ id: "5", name: "Naturaleza", slug: "nature", color: "#2BB7A6" }],
    coverImage: "https://picsum.photos/seed/sunset-rock/800/500",
    rating: 4.9,
    reviewCount: 71,
    departureTimes: ["16:00"],
    returnTime: "18:30",
    isFullDay: false,
    zone: "fuera-medellin",
    physicalIntensity: "medium",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 1,
    tags: ["tarde", "fotográfico", "romántico", "naturaleza"],
  },
  {
    id: "16",
    title: "Chiva Fiestera Cumpleaños",
    slug: "chiva-fiestera-cumpleanos",
    shortDescription: "Celebra tu cumpleaños o despedida en nuestra chiva parrandera con decoración, DJ y trago incluido.",
    priceFrom: 200000,
    currency: "COP",
    durationMinutes: 240,
    isFeatured: false,
    isOffer: false,
    destination: destMedellin,
    operator: opChivas,
    categories: [{ id: "4", name: "Fiesta", slug: "party", color: "#FFC97A" }],
    coverImage: "https://picsum.photos/seed/birthday-party/800/500",
    rating: 4.9,
    reviewCount: 58,
    departureTimes: ["19:00", "21:00"],
    returnTime: "01:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "low",
    operatingDays: [1, 2, 3, 4, 5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 2,
    tags: ["noche", "festivo", "adultos", "grupal", "privado", "eventos"],
  },
  {
    id: "17",
    title: "Chiva de las Flores",
    slug: "chiva-de-las-flores",
    shortDescription: "Recorre las calles de Medellín en la legendaria Chiva de las Flores durante la Feria de las Flores.",
    priceFrom: 130000,
    currency: "COP",
    durationMinutes: 180,
    isFeatured: false,
    isOffer: true,
    destination: destMedellin,
    operator: opChivas,
    categories: [{ id: "4", name: "Fiesta", slug: "party", color: "#FFC97A" }],
    coverImage: "https://picsum.photos/seed/flowers-festival/800/500",
    rating: 5.0,
    reviewCount: 29,
    departureTimes: ["18:00", "20:00"],
    returnTime: "23:00",
    isFullDay: false,
    zone: "centro",
    physicalIntensity: "low",
    operatingDays: [5, 6, 7],
    pickupIncluded: false,
    bookingAdvanceDays: 2,
    tags: ["noche", "festivo", "cultural", "familiar", "grupal"],
  },
];

export const mockTourDetails: Record<string, TourDetail> = {
  "guatape-full-day": {
    ...mockTours.find((t) => t.slug === "guatape-full-day")!,
    description: `El tour más popular de Antioquia. Comenzamos temprano desde Medellín en transporte cómodo con aire acondicionado. Al llegar a Guatapé, subimos la icónica Piedra del Peñol (740 escalones) para una vista panorámica espectacular del embalse y sus 69 islas.\n\nDespués, recorremos el colorido pueblo de Guatapé, famoso por sus zócalos pintados con escenas de la vida cotidiana. Al mediodía, disfrutamos de un almuerzo típico en restaurante a orillas del embalse.\n\nPor la tarde, subimos a bordo de una lancha privada para navegar por las aguas del embalse y conocer la isla de Pablo Escobar y otras islas privadas con sus fincas lujosas.`,
    meetingPoint: "Parque de las Luces, Medellín (frente al Centro Administrativo La Alpujarra)",
    capacityMin: 4,
    capacityMax: 16,
    includes: [
      "Transporte ida y vuelta desde Medellín",
      "Guía bilingüe (español/inglés)",
      "Entrada a la Piedra del Peñol",
      "Tour en lancha por el embalse (30 min)",
      "Almuerzo típico antioqueño",
      "Botella de agua",
    ],
    excludes: [
      "Gastos personales",
      "Souvenirs",
      "Propinas",
      "Snacks adicionales",
    ],
    images: [
      { url: "https://picsum.photos/seed/guatape-rock/1200/700", altText: "La Piedra del Peñol", isCover: true },
      { url: "https://picsum.photos/seed/guatape-lake/1200/700", altText: "Embalse de Guatapé", isCover: false },
      { url: "https://picsum.photos/seed/guatape-town/1200/700", altText: "Pueblo de Guatapé", isCover: false },
      { url: "https://picsum.photos/seed/guatape-boat/1200/700", altText: "Tour en lancha", isCover: false },
    ],
    itinerary: [
      { stepNumber: 1, title: "Salida desde Medellín", description: "Encuentro en el Parque de las Luces. Salida en transporte privado.", duration: "7:00 AM" },
      { stepNumber: 2, title: "Llegada a Guatapé y subida a la Piedra", description: "740 escalones hasta la cima con vista 360° del embalse.", duration: "9:30 AM – 11:00 AM" },
      { stepNumber: 3, title: "Recorrido por el pueblo colorido", description: "Caminata por las calles y zócalos pintados de Guatapé.", duration: "11:00 AM – 12:30 PM" },
      { stepNumber: 4, title: "Almuerzo típico antioqueño", description: "Bandeja paisa o trucha del embalse en restaurante con vista.", duration: "12:30 PM – 2:00 PM" },
      { stepNumber: 5, title: "Tour en lancha por el embalse", description: "Navegación privada: isla de Pablo Escobar, fincas y miradores acuáticos.", duration: "2:00 PM – 3:00 PM" },
      { stepNumber: 6, title: "Regreso a Medellín", description: "Salida desde el muelle hacia Medellín.", duration: "3:30 PM – 5:30 PM" },
    ],
    faqs: [
      { question: "¿Es apto para niños?", answer: "Sí, aunque la subida a la Piedra tiene 740 escalones. Recomendamos buena condición física. Los niños menores de 5 años no pagan entrada." },
      { question: "¿Qué debo llevar?", answer: "Ropa cómoda, protector solar, gorra, cámara y algo de efectivo para souvenirs y gastos adicionales." },
      { question: "¿El tour opera si llueve?", answer: "Sí, el tour opera en todas las condiciones climáticas. El tour en lancha puede ajustarse según el clima." },
      { question: "¿Puedo reservar para grupos privados?", answer: "¡Por supuesto! Contáctanos por WhatsApp para cotizaciones de grupos privados con transporte exclusivo." },
    ],
  },
  "turtle-bus-city-tour": {
    ...mockTours.find((t) => t.slug === "turtle-bus-city-tour")!,
    description: `Sube a bordo del icónico Turtle Bus y descubre Medellín desde una perspectiva única. Recorremos los barrios más representativos: El Centro Histórico, El Poblado, Laureles y Envigado, con paradas estratégicas en los mejores puntos de la ciudad.

Nuestros guías locales te contarán la historia de transformación de Medellín, sus proyectos de innovación urbana y los secretos de cada barrio. Un tour imprescindible para entender por qué Medellín es la ciudad más innovadora de Colombia.`,
    meetingPoint: "Hotel Dann Carlton, El Poblado",
    capacityMin: 2,
    capacityMax: 20,
    includes: [
      "Transporte en Turtle Bus",
      "Guía local bilingüe",
      "Visita a El Poblado, Laureles, El Centro",
      "Parada para foto en los mejores miradores",
      "Snack de bienvenida",
    ],
    excludes: ["Almuerzo", "Bebidas adicionales", "Propinas"],
    images: [
      { url: "https://picsum.photos/seed/medellin-bus/1200/700", altText: "Turtle Bus en Medellín", isCover: true },
      { url: "https://picsum.photos/seed/medellin-city/1200/700", altText: "Ciudad de Medellín", isCover: false },
      { url: "https://picsum.photos/seed/medellin-view/1200/700", altText: "Vista panorámica", isCover: false },
    ],
    itinerary: [
      { stepNumber: 1, title: "Encuentro y bienvenida", description: "Abordamos el Turtle Bus en El Poblado.", duration: "9:00 AM" },
      { stepNumber: 2, title: "El Poblado y Parque del Poblado", description: "El barrio más cosmopolita de Medellín.", duration: "9:15 AM – 10:00 AM" },
      { stepNumber: 3, title: "Laureles y Estadio", description: "Barrio residencial y gastronómico de los paisas.", duration: "10:00 AM – 10:45 AM" },
      { stepNumber: 4, title: "Centro Histórico", description: "Plaza Botero, Parque Berrío, Edificio Coltejer.", duration: "11:00 AM – 12:00 PM" },
    ],
    faqs: [
      { question: "¿Cuánto dura el tour?", answer: "Aproximadamente 3 horas, incluyendo las paradas fotográficas." },
      { question: "¿En qué idiomas se hace el tour?", answer: "En español e inglés. Para otros idiomas, contáctanos con anticipación." },
    ],
  },
};

export function formatPrice(price: number, currency = "COP"): string {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes} min`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h}h ${m}min` : `${h}h`;
}
